/*
 * L I M I T W 3 2 . H P P
 * (c) Charybdis Limited, 1995. All Rights Reserved.
 *
 * W A R N I N G
 * This file is automatically generated. Any edits will be lost.
 * The generated code is compatible with Watcom C++ ( 32 bit ).
 */

#ifndef _LIMITW32_HPP
#define _LIMITW32_HPP

//////////////////////////////////////////////////////////////////////

typedef signed char     int8;
typedef unsigned char	uint8;
typedef short		    int16;
typedef unsigned short  uint16;
typedef int		        int32;
typedef unsigned int	uint32;
typedef
  long long unsigned int uint64;

typedef float           float32;
typedef double          float64;

//////////////////////////////////////////////////////////////////////

#endif	/*	#ifndef _LIMITW32_HPP	*/


