/*
 * L I M I T W 1 6 . H P P
 * (c) Charybdis Limited, 1995. All Rights Reserved. 
 *
 * W A R N I N G 
 * This file is automatically generated. Any edits will be lost.
 * The generated code is compatible with Watcom C++ ( 16 bit ).
 */

#ifndef _LIMITW16_HPP
#define _LIMITW16_HPP

//////////////////////////////////////////////////////////////////////

typedef signed char	    int8;
typedef unsigned char	uint8;
typedef short		    int16;
typedef unsigned short	uint16;
typedef long		    int32;
typedef unsigned long	uint32;

//////////////////////////////////////////////////////////////////////

#endif	/* #ifndef _LIMITW16_HPP	*/


